services:
  - type: web
    name: anor-check
    env: python # On passe l'environnement à python pour que Render installe l'interpréteur
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
      npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18 # Assure-toi d'avoir une version récente de Node