name: anor_check
description: "Application officielle ANOR pour la certification des produits."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Gestion de la caméra haute précision
  camera: ^0.11.0
  # Communication sécurisée avec votre serveur
  http: ^1.2.0
  # Pour stocker et traiter les images avant envoi
  path_provider: ^2.1.2
  # Pour la géolocalisation silencieuse en arrière-plan
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true